START TRANSACTION;
USE `ducket-db`;
INSERT IGNORE INTO `ducket-db`.`currency` (`id`, `area`, `name`, `symbol`, `iso_code`) VALUES (DEFAULT, 'Poland', 'Polish złoty', 'zł', 'PLN');
INSERT IGNORE INTO `ducket-db`.`currency` (`id`, `area`, `name`, `symbol`, `iso_code`) VALUES (DEFAULT, 'EU', 'Euro', '€', 'EUR');
INSERT IGNORE INTO `ducket-db`.`currency` (`id`, `area`, `name`, `symbol`, `iso_code`) VALUES (DEFAULT, 'United States', 'United States dollar', '$', 'USD');

COMMIT;


START TRANSACTION;
USE `ducket-db`;
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'HOUSING', 'HOUSING');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'HOUSING', 'BUILDING_AND_REPAIR');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'HOUSING', 'MORTGAGE');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'HOUSING', 'RENT_PAYMENT');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'HOUSING', 'HOME_SECURITY');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'HOUSING', 'UTILITIES');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'HOUSING', 'HOME_MEDIA');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FOOD_AND_DRINKS', 'FOOD_AND_DRINKS');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FOOD_AND_DRINKS', 'CAFE');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FOOD_AND_DRINKS', 'RESTAURANTS_OR_BARS');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FOOD_AND_DRINKS', 'FOOD_DELIVERY_OR_TAKEOUT');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FOOD_AND_DRINKS', 'FASTFOOD');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FOOD_AND_DRINKS', 'GROCERY');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FOOD_AND_DRINKS', 'SPORT_NUTRITION');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'SHOPPING');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'GIFTS');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'HOME_SUPPLIES');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'ELECTRONICS_OR_APPLIANCES');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'BOOKS_OR_STATIONERY');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'PHARMACY');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'CLOTHES_OR_SHOES');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'ACCESSORIES_AND_EQUIPMENT');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'FURNITURE_AND_DECOR');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'DIGITAL_PRODUCTS');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'SERVICES');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FAMILY', 'FAMILY');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FAMILY', 'CHILD_SUPPLIES');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FAMILY', 'CHILD_HEALTHCARE');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FAMILY', 'CHILD_EDUCATION');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FAMILY', 'DAYCARE');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FAMILY', 'BABYSITTER');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FAMILY', 'PETS');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LEISURE', 'LEISURE');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LEISURE', 'HOBBY');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LEISURE', 'HOLIDAYS_AND_VACATIONS');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LEISURE', 'PUBLIC_EVENTS');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LEISURE', 'CINEMA_AND_THEATER');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LEISURE', 'GAMES');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'PERSONAL_CARE', 'PERSONAL_CARE');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'PERSONAL_CARE', 'WELLNESS_AND_BEAUTY');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'PERSONAL_CARE', 'HEALTHCARE');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'PERSONAL_CARE', 'EDUCATION');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'PERSONAL_CARE', 'SPORT_ACTIVITIES');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'TRANSPORT');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'PUBLIC_TRANSPORT');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'INTERCITY_TRANSPORT');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'RIDE_SHARING');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'TAXI');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'BUSINESS_TRIP');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'PETROL_AND_CHARGING');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'PERSONAL_VEHICLE');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'FINANCIAL_COSTS');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'INSURANCE');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'CHARGES_AND_FEES');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'LOANS_AND_DEBTS');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'TAXES');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'CHARITY');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'SUBSCRIPTIONS');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'MOBILE_PHONE');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'INTERNET');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'SERVICES');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'PARKING_LOT');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INVESTMENTS', 'INVESTMENTS');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INVESTMENTS', 'STOCKS_AND_SHARES');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INVESTMENTS', 'CRYPTO');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INVESTMENTS', 'NFT');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INVESTMENTS', 'REALTY');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INVESTMENTS', 'SAVINGS');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INCOME', 'INCOME');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INCOME', 'SALARY');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INCOME', 'CASHBACK_OR_REFUND');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INCOME', 'SELLING');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'OTHER', 'OTHER');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'OTHER', 'WITHDRAWAL');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'OTHER', 'TRANSFER');
INSERT IGNORE INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'OTHER', 'UNCATEGORIZED');

COMMIT;
