START TRANSACTION;
USE `ducket-db`;
INSERT INTO `ducket-db`.`currency` (`id`, `area`, `name`, `symbol`, `iso_code`) VALUES (DEFAULT, 'Poland', 'Polish złoty', 'zł', 'PLN');
INSERT INTO `ducket-db`.`currency` (`id`, `area`, `name`, `symbol`, `iso_code`) VALUES (DEFAULT, 'EU', 'Euro', '€', 'EUR');
INSERT INTO `ducket-db`.`currency` (`id`, `area`, `name`, `symbol`, `iso_code`) VALUES (DEFAULT, 'United States', 'United States dollar', '$', 'USD');

COMMIT;


START TRANSACTION;
USE `ducket-db`;
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'HOUSING', 'HOUSING');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'HOUSING', 'BUILDING_AND_REPAIR');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'HOUSING', 'MORTGAGE');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'HOUSING', 'RENT_PAYMENT');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'HOUSING', 'FURNITURE_AND_DECOR');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FOOD_AND_DRINKS', 'FOOD_AND_DRINKS');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FOOD_AND_DRINKS', 'CAFE');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FOOD_AND_DRINKS', 'RESTAURANTS_OR_BARS');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FOOD_AND_DRINKS', 'FOOD_DELIVERY');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FOOD_AND_DRINKS', 'FASTFOOD');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FOOD_AND_DRINKS', 'GROCERY');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FOOD_AND_DRINKS', 'SPORT_NUTRITION');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'SHOPPING');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'GIFTS');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'HOME_SUPPLIES');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'ELECTRONIC_GOODS');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'BOOKS_OR_STATIONERY');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'JEWELS');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'PHARMACY_OR_CHEMICALS');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'CLOTHES_AND_ACCESSORIES');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'SOFTWARE');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'SHOPPING', 'SERVICES');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'CHILDREN', 'CHILDREN');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'CHILDREN', 'CHILD_SUPPLIES');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'CHILDREN', 'CHILD_HEALTHCARE');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'CHILDREN', 'DAYCARE');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'CHILDREN', 'CHILD_EDUCATION');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'CHILDREN', 'BABYSITTER');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'PETS', 'PETS');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'PETS', 'PETS_SUPPLIES');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'PETS', 'PETS_HEALTHCARE');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LIFE_AND_LEISURE', 'LIFE_AND_LEISURE');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LIFE_AND_LEISURE', 'SPORT_ACTIVITIES');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LIFE_AND_LEISURE', 'CHARITY');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LIFE_AND_LEISURE', 'EDUCATION');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LIFE_AND_LEISURE', 'HEALTHCARE');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LIFE_AND_LEISURE', 'GAMES');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LIFE_AND_LEISURE', 'CINEMA_AND_THEATER');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LIFE_AND_LEISURE', 'PUBLIC_EVENTS');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LIFE_AND_LEISURE', 'HOLIDAYS_AND_VACATIONS');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LIFE_AND_LEISURE', 'WELLNESS_AND_BEAUTY');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'LIFE_AND_LEISURE', 'HOBBY');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'TRANSPORT');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'PUBLIC_TRANSPORT');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'INTERCITY_TRANSPORT');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'RIDE_SHARING');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'TAXI');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'BUSINESS_TRIP');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'PETROL_AND_CHARGING');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'TRANSPORT', 'PERSONAL_VEHICLE');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'UTILITIES', 'UTILITIES');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'UTILITIES', 'HOME_MEDIA');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'UTILITIES', 'MOBILE_PHONE');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'UTILITIES', 'ELECTRICITY');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'UTILITIES', 'WATER');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'UTILITIES', 'GAZ');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'FINANCIAL_COSTS');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'INSURANCE');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'CHARGES_AND_FEES');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'LOANS_AND_DEBTS');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'TAXES');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'SUBSCRIPTIONS');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'WITHDRAWAL_OR_TRANSFER');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'FINANCIAL_COSTS', 'PARKING_LOT');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INVESTMENTS', 'INVESTMENTS');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INVESTMENTS', 'STOCKS_AND_SHARES');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INVESTMENTS', 'CRYPTO');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INVESTMENTS', 'REALTY');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INVESTMENTS', 'SAVINGS');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INFLOW', 'INFLOW');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INFLOW', 'SALARY');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INFLOW', 'REIMBURSEMENT');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'INFLOW', 'SELLING');
INSERT INTO `ducket-db`.`category` (`id`, `group`, `name`) VALUES (DEFAULT, 'UNCATEGORIZED', 'UNCATEGORIZED');

COMMIT;
